spring:
  application.name: membership
  autoconfigure.exclude: org.springframework.cloud.netflix.servo.ServoMetricsAutoConfiguration
security.basic.enabled: false
netflix:
  appinfo.name: ${spring.application.name}
  appinfo.region: us-west-1
  environment: test
  atlas.uri: http://localhost:7101/api/v1/publish
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
server.port: 8080
netflix.spectator.rest.maxAge: 2000
